price1 = float(input("ราคาสินค้า 1"))
amount1 = int(input("จำนวนสินค้า 1"))
price2 = float(input("ราคาสินค้า 2"))
amount2 = int(input("ราคาสินค้า 2"))
total=(price1 * amount1) + (price2 * amount2)
print("ค่าใช้จ่ายของคุณครั้งนี้ คือ \n" , total , "บาท")